# Generated by Django 3.1.6 on 2021-03-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210304_2058"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="type",
            field=models.CharField(
                choices=[("RSS", "Rss"), ("Reddit", "Reddit"), ("Twitter", "Twitter")],
                default="RSS",
                max_length=10,
            ),
        ),
    ]
