# Generated by Django 3.1.6 on 2021-03-14 07:46

from django.db import migrations

from core.models import Feed


def update_extras(apps, schema_editor):
    fd = apps.get_model('core', 'Feed')
    for f in fd.objects.filter(type=Feed.Type.RSS):
        f.extras.pop('filter', None)
        f.extras['filtered'] = []
        f.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20210314_0729'),
    ]

    operations = [
        migrations.RunPython(update_extras)
    ]
