# Generated by Django 3.1.6 on 2021-03-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20210314_0735"),
        ("core", "0007_auto_20210314_0746"),
    ]

    operations = []
