# Generated by Django 3.1.6 on 2021-03-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_merge_20210314_0749"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="filter",
        ),
    ]
