# Generated by Django 3.1.6 on 2021-06-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_feed_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='type',
            field=models.CharField(choices=[('RSS', 'Rss'), ('Reddit', 'Reddit'), ('Twitter', 'Twitter'), ('Mail', 'Mail')], default='RSS', max_length=10),
        ),
    ]
