# Generated by Django 3.1.6 on 2021-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210627_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='tag',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
