# Generated by Django 3.1.6 on 2021-07-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210703_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-position']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='position',
            field=models.IntegerField(default=-1),
        ),
    ]
