# Generated by Django 3.1.6 on 2021-07-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210709_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
