# Generated by Django 3.1 on 2022-05-21 07:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220306_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=core.models.get_now),
        ),
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=core.models.get_now),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=core.models.get_now),
        ),
    ]
