# Generated by Django 3.1 on 2022-05-21 07:38
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220521_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='guid',
            field=models.TextField(null=True),
        ),
    ]
