# Generated by Django 3.1 on 2022-05-21 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_auto_20220521_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='guid',
            field=models.TextField(unique=True),
        ),
    ]
